### ISSUE TITLE
Anova function to accept Y array and Y cap array

### ISSUE THREAD

**Issue by RuhiA** [RuhiA/cce-data-analytics#4]
Hi Upasana, Please let me know if it possible for you to change the function to Accept Y array(observed value) and Ycap ( estimated value) and the number of estimated parameters (m).

**Comment by RuhiA** [comment]
def calculate_f_statistic(self, y_arr, ycap_arr, m, alpha_value):
        # Validating inputs
        dfr = m -1

        if len(y_arr) != len(ycap_arr):
            raise ValueError('Mismatch in the size of y and ^y arrays')

        return self.compute_anova(y_arr,ycap_arr, dfr, alpha_value)

**Comment by upasana1708** [comment]
I have committed the code to accept y_cap array directly as method argument

**Comment by RuhiA** [comment]
Thanks !!
